def silly():
	print("Let's play Silly Sentences! \n")
	name=input("Enter a name: ")
	adj=input("Enter an adjective: ")
	adj2=input("Enter an adjective: ")
	adv=input("Enter an adverb: ")
	food=input("Enter a food: ")
	food2=input("Enter another food: ")
	noun=input("Enter a noun: ")
	place=input("Enter a place: ") 
	verb=input("Enter a verb: \n")
	print(name + " was planning a dream vacation to " + place + "." )
	print(name + " was especially looking forward to trying the local")
	print("cuisine, including " + adj + " " + food + " and " + food2 + ". \n")
	print(name + " will have to practice the language " + adv +" to")
	print("make it easier to " + verb +" with people. \n")
	print(name + " has a long list of sights to see, including the")
	print(noun + " museum and the " + adj2 + " park.")